name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Git
      run: sudo apt update && sudo apt install -y git
    - name: Download and install Fossil
      run: wget -O fossil.tgz https://www.fossil-scm.org/home/uv/fossil-linux-x64-2.14.2.tar.gz && tar xvf fossil.tgz && sudo cp fossil /usr/local/bin/
    - name: Print versions
      run: fossil version && git version
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run tests
      run: ./tests/fossil-wiki-export.test
