name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Git
      run: sudo apt update && sudo apt install -y fossil git
    - name: Print versions
      run: fossil version && git version
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run tests
      run: tests/fossil-wiki-export.test
